### ISSUE TITLE
Resources on animation in web design

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-motion#1]
- UI Animation Reviews: Animation In Responsive Design - All The Right Moves Screencast: https://vimeo.com/131224232
- FLIP your animations: https://aerotwist.com/blog/flip-your-animations/
- What news readers want: http://paul.kinlan.me/what-news-readers-want/ (answer: [smooth navigation](http://paul.kinlan.me/images/news-app-features.png))

Please share additional resources here.

**Comment by phamann** [comment]
Google Material Design animation guidelines:

- [Authentic motion](https://www.google.com/design/spec/animation/authentic-motion.html#)
- [Responsive interaction](https://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-surface-reaction)
- [Meaningful transitions](https://www.google.com/design/spec/animation/meaningful-transitions.html)
- [Delightful transitions](https://www.google.com/design/spec/animation/delightful-details.html)

**Comment by phamann** [comment]
- Tim Kadlec's "In Between": https://vimeo.com/125657468

**Comment by hteumeuleu** [comment]
* Invisible animation : https://medium.com/@stevenfabre/invisible-animation-ffa27d0b77e5
* The art of UI animations : http://markgeyer.com/pres/the-art-of-ui-animations/
* Making things move when you are a front end developer : http://guillaumegouessan.com/talk/move/
* Web Animation Resources : http://www.benjystanton.co.uk/about/web-animation-resources/

**Comment by kaelig** [comment]
[Google Polymer's Neon Animation](https://github.com/PolymerElements/neon-animation): `neon-animation` is a suite of elements and behaviors to implement pluggable animated transitions for Polymer Elements using Web Animations.

**Comment by jaicab** [comment]
- Val Head's ["Putting your UIs in motion"](https://vimeo.com/125545020) and [notes from Luke W.](http://www.lukew.com/ff/entry.asp?1858).
- Yesenia Perez-Cruz's ["Resources for web animations"](http://alistapart.com/blog/post/dive-in-resources-for-web-animation)
- [Easing functions] (http://www.kirupa.com/html5/easing_functions_css3.htm).

**Comment by kaelig** [comment]
- [Benjamin De Cock - Lets move! - CSS Conf AU](https://www.youtube.com/watch?v=J6wUmQDQBkw)
- [Steven Fabre - Invisible animation - CSS Conf AU](https://www.youtube.com/watch?v=XlaX2TumAPI)

**Comment by kaelig** [comment]
There's a new podcast with a ton of links to great resources in the show notes: http://motionandmeaning.io/

Totally recommended if you want to know where to start with web animation.

**Comment by pauloneillft** [comment]
Some nice button loading feedback examples. https://github.com/hakimel/Ladda
http://lab.hakim.se/ladda/

**Comment by pauloneillft** [comment]
Google's Material principles are a good starting point for good general principles I think.
http://www.google.com/design/spec/animation/meaningful-transitions.html#meaningful-transitions-visual-continuity

**Comment by charypar** [comment]
Spring physics based animations and interactions.

* http://iamralpht.github.io/physics/
* http://matthaeuskrenn.com/springto/ (edited)
* https://github.com/julianshapiro/velocity, and I'll stop now

Nice benefit of these is they compose well and are quite declarative.
