### ISSUE TITLE
Scope: animations, transitions, best practices…

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-motion#2]
What should be the scope of this module?

Here are a few ideas:
- JavaScript animation helpers
- CSS animations helpers
- Transition/animation timing values (e.g. in Sass mixins and variables + JavaScript config files)
- Performance best practices
- Motion design principles on the web
- Metaphors and design thinking behind FT-like motion

**Comment by origamiserviceuser** [comment]
This is a good article in that it made me aware of something I'd not really thought about before: http://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity

**Comment by kaelig** [comment]
The IBM design team did an amazing work at combining all of the thinking, best practices, tips and tricks, tools… in a few pages: http://www.ibm.com/design/language/framework/animation/fundamentals
