### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-motion#3]
Please list use-cases in this thread to help figure out the scope of this module (see #2).

**Comment by wheresrhys** [comment]
- notification bar on next (follow something to see it)
 - we need some kind of progress indicator
 - animated expander

**Comment by kaelig** [comment]
- Buttons: save / unsave, follow / unfollow
- More/fewer stories button -> showing/hiding content (maybe same as "expander" mentioned by @wheresrhys)
