### ISSUE TITLE
Prototyping tools

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-motion#5]
- InVision http://www.invisionapp.com/
- Marvel https://marvelapp.com/
- Adobe After Effects
-  Keynote
- Framer http://framerjs.com/

(thanks to @antoineplu for these)

Please add suggestions below (and please don't say "Flash" :dromedary_camel:).

**Comment by kaelig** [comment]
- Atomic https://atomic.io/
- Form http://www.relativewave.com/form/
- Pixate http://www.pixate.com/
- Proto.io https://proto.io/
- UXPin https://www.uxpin.com

Source: https://medium.com/@kunalslab/the-new-generation-of-prototyping-tools-part-1-2-c01105310b6b

**Comment by kaelig** [comment]
- Easee https://easee.design/ (built by @stevenfabre who improved the Campaign Monitor email editor by bringing meaning through animation)

**Comment by samgiles** [comment]
This looks like a cool way of trying some animations on an existing page:

http://anijs.github.io/studio/

**Comment by AntoinePlu** [comment]
* Flinto
* Origami
* Axure

Other tools and a great comparison table here : [cooper.com/prototyping-tools](http://www.cooper.com/prototyping-tools)

**Comment by kaelig** [comment]
Thanks again @AntoinePlu, that link is very useful.

**Comment by AntoinePlu** [comment]
And I forgot, if you are more :pencil2: & :page_facing_up: , there is POP (Prototype on Paper) : https://popapp.in/

**Comment by kaelig** [comment]
- Sequence.js http://www.sequencejs.com/
